---
title: "generating figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=TRUE, warning = FALSE)
library(tidyverse)
library(storywranglr)
library(lubridate)

figures <- read_csv ("../data/figures.csv")

# # function used to parse SW data and get it tidy
# make_sw_plotready <- function(sw, start_date) {
#   mutate(sw, across(where(is.numeric), function(x) if_else(is.na(x), 0, x)),
#          rank = if_else(rank==0, 1000000, rank),
#          rank_no_rt = if_else(rank_no_rt==0, 1000000, rank_no_rt)) %>%
#     select(date, rank, query) %>%
#     filter(date >= start_date) %>%
#     arrange(date) %>%
#     distinct() %>%
#     pivot_wider(names_from = date, values_from = rank, values_fill = 1000000) %>%
#     pivot_longer(cols = -query,
#                  names_to = "date",
#                  values_to = "rank")
#   
# }

sw_data <- read_csv("../data/storywrangler_gym_terms_forplot_2021-10-29a.csv") 



```


```{r get_data, eval = FALSE}

get_sw_data <- function(figures) {
  df <- figures %>%
    mutate(sw = purrr::map(ngram, storywranglr::ngrams))
  
  test <- df %>%
    unnest(cols = c(sw)) #%>%    make_sw_plotready(start_date = "2015-01-01")
  
  return(test)
  
}

sw_data <- get_sw_data(figures)

write_csv(sw_data, "../data/storywrangler_gym_terms_forplot_2021-10-29a.csv")

```





```{r message=TRUE}

for (i in 1:nrow(figures)){
  ngram_now <- figures$ngram[[i]]
  group <- figures$group[[i]]
  description <- figures$description[[i]]
  
  num <- (i-1) %% 3 + 1
  
  filename <- sprintf("%s%s - %s (%s).png", group, num, ngram_now, description)
  message(filename)
  print(filename)
  
  df <- sw_data %>% filter(ngram == ngram_now)
  
  fig <- df %>%
    storywranglr::plot_contagiogram(min_date = "2018-01-01", fig_theme = "jsr")
  
  #fig
  ggsave(plot = fig,
         filename = paste0("figs/storywrangler/", filename),
          width = 5.24,
         height = 4.17
  )
  
  
}


```

# google trends


```{r}
min_date <- lubridate::as_date("2018-01-01")
max_date <- lubridate::as_date("2021-10-29")
vline_date <- "2020-03-11"

# gt <- figures %>%
#   mutate(gtrends = purrr::map(gterm, gtrendsR::gtrends, geo = "US", time = "2018-01-01 2021-10-29"))
# 
# 
# gtrends <- gt %>%
#   mutate(gt = purrr::map(gtrends, pluck, "interest_over_time")) %>%
#   unnest(cols = c(gt))
# 
# write_csv(select(gtrends, -gtrends), "../data/google_trends_2021-10-29.csv")

gtrends <- read_csv("../data/google_trends_2021-10-29.csv")

for (i in 1:nrow(figures)){
  gterm_now <- figures$gterm[[i]]
  group <- figures$group[[i]]
  description <- figures$description[[i]]
  
  num <- (i-1) %% 3 + 1
  
  filename <- sprintf("%s%s - %s - %s (%s).png", group, num, "gtrend", gterm_now, description)
  message(filename)
  
  
  forplot <- gtrends %>%
    filter(gterm == gterm_now)
  
  if (min(forplot$date) > lubridate::as_date(min_date)) forplot <- add_row(forplot, date = as_date(min_date, hits= NA))
  if (max(forplot$date) < lubridate::as_date(max_date)) forplot <- add_row(forplot, date = as_date(max_date, hits= NA))
  
  fig <- forplot %>%
    mutate(date = as_date(date)) %>%
    arrange(date) %>%
    filter(date >= min_date & date <= max_date) %>%
    ggplot() + 
    geom_line(aes(x=date, y=hits),
              size = 1) +
    ggplot2::geom_vline(xintercept = as.Date(vline_date),
                        colour = "black", linetype = "dashed") +
    theme_minimal() +
    ggplot2::scale_y_continuous(expand = c(0,0)) +
    ggplot2::scale_x_date(expand = c(0,0)) +
    ggplot2::labs (x = NULL, y = NULL) +
    labs(title = sprintf("Google Trends: '%s'", gterm_now)) +
     ggplot2::theme(plot.title = element_text(hjust = 0.5)) 
  
  
    #fig
  ggsave(plot = fig,
         filename = paste0("figs/gtrends/", filename),
          width = 5.24,
         height = 4.17
  )
  
}
```


# heat maps

```{r}

gym_forplot <- read_csv("../data/storywrangler_gym_terms_forplot.csv")

gym_forplot %>%
  ggplot() +
  geom_tile(aes(x=date, y=query, fill = rank)) +
  geom_vline(xintercept = as_date("2020-03-11")) +
  scale_fill_continuous(
    trans = ggforce::trans_reverser("log"), 
    type = "gradient",
    low = "#000000", high = "#FFFFFF",
    breaks= 10^(1:6),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  labs(x = NULL, y = NULL, fill = "Rank") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  scale_x_date(expand = c(0.01,0)) 

```

```{r}
covid_forplot <- read_csv("../data/covid_data_forplot.csv")


fig <- covid_forplot %>%
  ggplot() +
  geom_tile(aes(x=date, y=query, fill = rank)) +
  geom_vline(xintercept = as_date("2020-03-11")) +
  scale_fill_continuous(
    trans = ggforce::trans_reverser("log"), 
    #type = "viridis",
        type = "gradient",
    low = "#000000", high = "#FFFFFF",
    breaks= 10^(1:6),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  labs(x = NULL, y = NULL, fill = "Rank") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  scale_x_date(expand = c(0.01,0))

ggsave(plot = fig, filename = "figs/heatmaps/covid_heatmap.png")
```

